// <auto-generated />
namespace mvcOnlineTicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class kargoBilgi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kargoBilgi));
        
        string IMigrationMetadata.Id
        {
            get { return "202301182106093_kargoBilgi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
